name = "indo" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "mssdk24-normal-useast2a.tiktokv.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "autodiscover.instagram.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "m.instagram.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "hwvip.iflix.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "z-p15.www.instagram.com.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.indo.aghill.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.indo.aghill.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "0743e049-53d0-4f8a-bce4-b52c80b8b863"
